version: "2.1"

services:
  db:
    image: mysql:8.0
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rpwd
      - MYSQL_DATABASE=mycompany
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=mpwd
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
  app:
    image: jva/php-apache
    container_name: php-apache
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
